# Generated by Django 6.1.1 on 2026-09-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.IntegerField(default=1500),
        ),
    ]
