# Generated by Django 6.1.1 on 2026-09-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0002_region_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='arriendos.comuna'),
        ),
    ]
